//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hr.Web.Controls.Layout {
    
    
    public partial class HeaderTop {
        
        /// <summary>
        /// ctrlCompanyLogo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hr.Web.Controls.Layout.CompanyLogo ctrlCompanyLogo;
        
        /// <summary>
        /// ctrlLoggedOnOrOff control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hr.Web.Controls.Layout.LoggedOnOrOff ctrlLoggedOnOrOff;
    }
}
